name: PR / Push CI
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -q
      - name: Quick train (artifact)
        run: |
          python src/train.py --model linear --seed 42 --version ci-smoke --out-dir ci/artifacts
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: ci/artifacts

